### ISSUE TITLE
Add goroutine count check

### ISSUE THREAD

**Issue by alexliesenfeld** [alexliesenfeld/health#38]
It would be useful to have a small library of commonly used health checks. In the scope of this issue, a goroutine count check should be implemented (e.g. calling an `count := runtime.NumGoroutine()` and se if it is above a throeshold.

A few constraints to keep things clean and simple: 

* The check should be added to the [checks](https://github.com/alexliesenfeld/health/tree/development/checks) module that you can find in the `development` branch. 
* As with all health check functions of this library, the check implementation should support accepting and forwarding `context.Context` that is being passed to each health check function.  
* If the health check requires external external modules or other dependencies, the check should be implemented as a separate Go module(similarly how it is done for the tests, that require dependencies to other packages as well). This is required to avoid that when people import the base library, they also need to import all dependencies of all provided checks. 
* The check should have a README.md in its root directory that describes how to use it and maybe what to look out for. 
* You should provide a test that checks at least the happy path. If a docker container is required to properly test the check, the docker container can be added to the docker-compose.yaml file in the checks base package. 

Should you have questions or require help, please join our [discord chat room](https://discord.gg/f5dhR4H3vA).

**Comment by BulkBeing** [comment]
@alexliesenfeld  May I implement this one
