### ISSUE TITLE
Add panic recovery mechanism

### ISSUE THREAD

**Issue by alexliesenfeld** [alexliesenfeld/health#62]
When a user created health check function panics, this health check library currently does not provide a means to recover from it automatically and continue. Instead, the application terminates. This behaviour is most likely is not wanted. Therefore, this library should provide a way to recover from panics right after the check function call (e.g.: [here](https://github.com/alexliesenfeld/health/blob/0cc0d44f7be6ffa7a759e27c57c7f67e6444e92e/check.go#L371)). The user should 

* be able to able to opt out of this by configuration (e.g. by disabling it with a configuration option) and
* instead of panicking, the library should instead return an error.

**Comment by revisited-contrast** [comment]
Working on this, I am still learning Go but this seems pretty simple.

**Comment by revisited-contrast** [comment]
Whoops, looks like it's already implemented. My mistake.

**Comment by AMK9978** [comment]
I'm new at Golang either. So It should be closed.
