### ISSUE TITLE
Make health check runnable by name

### ISSUE THREAD

**Issue by PV99** [alexliesenfeld/health#67]
Currently, the Checker interface exposes a method `Check(ctx context.Context) CheckerResult` which runs all synchronous health checks. It should be possible to add a new method `CheckByName(ctx context.Context, name string) (CheckResult, CheckerResult)` which allows execution of a single synchronous check by name.

**Comment by PV99** [comment]
I'm happy to take this on, can you assign this to me?

**Comment by alexliesenfeld** [comment]
Hi @PV99 , thanks for creating this issue. Could you please elaborate a little bit what your use case is?

**Comment by PV99** [comment]
Hey @alexliesenfeld. A first use case is for checks that we only want runnable by admins. Sometimes, permissions to use the api's defined in a check change from environment to environment (e.g. permissions to access the redis-configuration api to execute the redis check-aof function may change from one customer to another). In these cases, these checks can and should only be triggered by an admin. 

A second use case is if we have more expensive application level checks which should not be run under high traffic or we only want to run after upgrades. In these cases, these checks should only manually be executed by name when appropriate. 

^ Understandably, health checks are generally very quick and non-expensive. However, this framework already has many other useful features so it would be a shame to have to build a separate framework to run manual checks.

**Comment by PV99** [comment]
Hey @alexliesenfeld, here are some rough thoughts on what the design would look like. 


### Base Design 
1. Update the Checker Interface with a new method: 
`CheckByName(ctx context.Context, name string) (CheckResult, CheckerResult, error)`

2. Implement this method in defaultChecker: 

```
// CheckByName implements Checker.CheckByName. Please refer to Checker.CheckByName for more information.
func (ck *defaultChecker) CheckByName(ctx context.Context, name string) (CheckResult, CheckerResult, error) {
        var (
		resChan            = make(chan checkResult, 1)
	)
        ck.mtx.Lock()
	defer ck.mtx.Unlock()

	ctx, cancel := context.WithTimeout(ctx, ck.cfg.timeout)
	defer cancel()

        check, ok := ck.cfg.checks[name]
        if not ok { 
                return checkResult{}, ck.mapStateToCheckerResult(), fmt.Errorf("Check with name: '%s' is not registered in Checker")
        }
        checkState := ck.state.CheckState[name]
        if !isPeriodicCheck(check) && isCacheExpired(ck.cfg.cacheTTL, &checkState) {
                
                withCheckContext(ctx, check, func(ctx context.Context) {
			_, checkState := executeCheck(ctx, &ck.cfg, check, checkState)
                         resChan <- checkResult{check.Name, checkState}
		})
        }
        checkResult := <- resChan 
        ck.updateState(ctx, checkResult)
	return checkResult, ck.mapStateToCheckerResult(), nil
}
```

This feature alone would be a huge win. If we wanted, we could run most checks via `Checker.Check`. But if there were a few checks we only wanted to run manually, we could maintain a second `Checker` with all the manual checks and run them via `Checker.CheckByName`. 

### Extensions 

Maintaining a second `Checker` would be somewhat annoying for users of this API. To take this design even further and only maintain one checker, we could also introduce a notion of "manual" checks which don't get triggered by default with Checker.Check, but can be triggered by Checker.CheckByName: 

1. Update the `Check` struct with a `manual: bool` field

```
Check struct {
		// The Name must be unique among all checks. Name is a required attribute.
		Name string // Required

	         ... 
	         
		initialDelay   time.Duration
		
		isManual      bool
	}
```

2. Introduce a new `WithManualCheck` method: `` 

```
// WithManualCheck adds a new health check that contributes to the overall service availability status.
 // This check will NOT be triggered when Checker.Check is called, but may be invoked manually via 
// Checker.CheckByName. 
func WithManualCheck(check Check) CheckerOption {
	return func(cfg *checkerConfig) {
                 check.isManual = true
		cfg.checks[check.Name] = &check
	}
}
```

3. Add an `IsManualCheck` method: 

```
func isManualCheck(check *Check) bool {
	return check.isManual
}
```

4. Update `runSynchronousChecks` to run all synchronous, non-manual checks 

```
func (ck *defaultChecker) runSynchronousChecks(ctx context.Context) {
	...
	for _, c := range ck.cfg.checks {
		checkState := ck.state.CheckState[c.Name]
		if !isPeriodicCheck(c) && !isManualCheck(c) && isCacheExpired(ck.cfg.cacheTTL, &checkState) {
			...
		}
	}
        ...
}
```

5. Finally, update the interface so that `Checker.Check` reflects that it runs synchronous checks sans manual checks. 
```
// Check runs all synchronous (i.e., non-periodic) check functions sans
// manual check functions. It returns the aggregated health status 
// (combined from the results of this executions synchronous checks and 
// the previously reported results of asynchronous/periodic checks. This 
// function expects a context, that may contain deadlines to which will be 
// adhered to. The context will be passed to all downstream calls (such as 
// listeners, component check functions, and interceptors).
Check(ctx context.Context) CheckerResult
```

Let me know of the base design and the extension make sense (even just implementing the base design would be helpful).

**Comment by alexliesenfeld** [comment]
What would you think about adding a `Skipper` to a `Check` config instead (similar how it's done in Echo, see here: https://echo.labstack.com/middleware/#skipping-middleware)

**Comment by PV99** [comment]
Hey Alex, a Skipper seems like a great solution. I'd be happy to implement that feature. If we merge this feature in, would you be willing to publish a new version of this package that would have the feature?

**Comment by alexliesenfeld** [comment]
@PV99 Yes, bu I think it will require quite a bit of refactoring. A few things that come into my mind are:

* For both, synchronous and periodic checks, a `Skipper` should probably skip the result in the aggregated result. For synchronous checks, a skipper probably should also skip the execution of the synchronous check. 
* At the moment, this library keeps a global state with an aggregated result that is computed based of all individually configured check functions. If the health endpoint would now get requests that only include a subset of the checks, a global aggregated state may not be representative for the response (imagine a check A is "down", but the HTTP request skips A, the cached overall aggregated result is still "down"). Hence, we would need to exclude skipped checks from the aggregated result, but this means that (1) caching the overall result is not useful anymore and (2) the overall result needs to be reevaluated on every HTTP request. 
* This library supports `Interceptors`, that may listen to global status changes (e.g., to log global system health status changes). When we would have a `Skipper`, it's unclear at the moment what the best behaviour would be when one request evaluates checks A,B,C and another request D,E,F with different aggregated results.

It may be an alternative to use different health endpoints that expose different checks (e.g., one "admin" endpoint, and one generic endpoint). This would mean that the checks need to be executed twice though, but that may not be a problem.
