### ISSUE TITLE
In actual response content type is text/plain even for (default) http.JSONResultWriter

### ISSUE THREAD

**Issue by panta** [alexliesenfeld/health#9]
This doesn't happen with unit tests, maybe there is a difference when using `httptest`?
With a real handler I get the response with a `text/plain` Content-Type. I guess this is because the [status is emitted](https://github.com/alexliesenfeld/health/blob/v0.5.1/handler.go#L75) before [the Content-Type](https://github.com/alexliesenfeld/health/blob/v0.5.1/handler.go#L76) ([ultimately set here](https://github.com/alexliesenfeld/health/blob/v0.5.1/handler.go#L50)).

**Comment by alexliesenfeld** [comment]
I understand. This is because [WriteHeader](https://golang.org/pkg/net/http/#ResponseWriter) is called before all headers are set (compare with https://github.com/golang/go/issues/17083).

**Comment by alexliesenfeld** [comment]
I think the ResultWriter needs to write the status code as well. Otherwise we will need to split the functionality to multiple functions or there will be ordering issues. The [develop branch](https://github.com/alexliesenfeld/health/tree/develop) has a fix for this.
